### ISSUE TITLE
Research/Implement: GroceryBear API

### ISSUE THREAD

**Issue by fremen432** [fremen432/Eazy-Eatz#6]
## User Story:
- AS A Developer,
I WANT to be able to understand and use GroceryBear API
SO THAT I can reference prices for specific ingredients
## Acceptance Criteria
- GIVEN an API with grocery prices
WHEN I "fetch()" this API
THEN I can store the values for ingredients and re-use them later

**Comment by Dakota3214** [comment]
GroceryBear does not accurately support all ingredients just less than 10 items, switching API to use Spoonacular API.
